language: ruby
rvm:
  - 2.2.2
services: 
  - postgresql
  - elasticsearch
env:
  - ELASTICSEARCH_HOST=localhost:9200
before_script:
  - cp config/database.travis.yml config/database.yml
  - psql -c 'create database v2_testing' -U postgres
  - sleep 10