# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1f281d2e700ab7f029925b67e36627bb0bda60d09c6b5de87322f347d9ca4dfff749c4d358990b6ae531ca8d02fe28258e93b8876fde5206751a96e8dad66061

test:
  secret_key_base: a73d835a6893364622bc228ae009456d2a1f674d0904c47886d3f56e4660e55e49e10fc014545322965a36094e9bcae8dd0cba30669b40564284fda4009ee3f0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
